# Generated by Django 5.0.6 on 2024-07-27 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_rename_bookings_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='rice',
            new_name='price',
        ),
    ]
